import type { NextPage } from "next";
import { useContext, useEffect } from "react";
import { CrowdfundContext } from "src/context/CrowdfundContext";
import { MediaContext } from "src/context/MediaContext";
import Head from "next/head";
import Navbar from "src/components/navbar";
import Attribution from "src/components/attribution";
import Landing from "src/components/landing";
import { ColorScheme } from "src/enums/colorScheme";

const Home: NextPage = () => {
  const { connectWallet, currentUser } = useContext(CrowdfundContext);
  const { deviceWidth } = useContext(MediaContext);

  useEffect(() => {
    console.log(`Device width: ${deviceWidth}`);

    if (document) {
      const root = document.querySelector(":root") as HTMLElement;
      const rootStyle = root.style;
      if (currentUser?.id) {
        rootStyle.setProperty("--main-bg-color", ColorScheme.LIGHT_GRAY);
        rootStyle.setProperty(
          "--attribution-font-color",
          ColorScheme.DARK_BLUE
        );
      } else {
        rootStyle.setProperty("--main-bg-color", ColorScheme.DARK_BLUE);
        rootStyle.setProperty(
          "--attribution-font-color",
          ColorScheme.LIGHT_GRAY
        );
      }
    }
  }, [currentUser]);

  return (
    <>
      <Head>
        <title>Fundfinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-online.svg" />
      </Head>
      <Navbar />
      <main>
        {currentUser && currentUser.id ? <>HI</> : <Landing />}
        <Attribution />
      </main>
    </>
  );
};

export default Home;
