import type { NextPage } from "next";
import { useContext, useEffect } from "react";
import { CrowdfundContext } from "src/context/CrowdfundContext";
import { MediaContext } from "src/context/MediaContext";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  const { connectWallet, currentUser } = useContext(CrowdfundContext);
  const { deviceWidth } = useContext(MediaContext);

  useEffect(() => {
    console.log(`Device width: ${deviceWidth}`);
  });

  return (
    <div>
      <button
        onClick={(e) => {
          e.preventDefault();
          connectWallet();
        }}
      >
        CONNECT WALLET
      </button>
      <h5>{currentUser?.id ? currentUser.id : "NO USER"}</h5>
      <Head>
        <title>Fundfinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-online.svg" />
      </Head>
    </div>
  );
};

export default Home;
