import type { NextPage } from "next";
import { useContext, useEffect } from "react";
import { CrowdfundContext } from "src/context/CrowdfundContext";
import { MediaContext } from "src/context/MediaContext";
import Head from "next/head";
import Navbar from "src/components/navbar";
import styles from "styles/Home.module.css";
import { consumers } from "stream";
import LandingHero from "src/components/landingHero";

const Home: NextPage = () => {
  const { connectWallet, currentUser } = useContext(CrowdfundContext);
  const { deviceWidth } = useContext(MediaContext);

  useEffect(() => {
    console.log(`Device width: ${deviceWidth}`);

    if (document && document.body) {
      if (currentUser?.id) {
        document.body.style.backgroundColor = "hsl(0, 0%, 98%)";
      } else {
        document.body.style.backgroundColor = "hsl(233, 26%, 24%)";
      }
    }
  }, [currentUser]);

  return (
    <>
      <Head>
        <title>Fundfinder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-online.svg" />
      </Head>
      <Navbar />
      <main className={styles.home}>
        {currentUser && currentUser.id ? (
          <></>
        ) : (
          <>
            <LandingHero />
          </>
        )}
      </main>
    </>
  );
};

export default Home;
