export enum ContractActions {
    WALLET_CHECK_CONNECTION = 'WALLET CHECK CONNECTION',
    WALLET_CONNECT = 'WALLET CONNECT',

    CURRENT_USER = 'CURRENT USER',
    ACCOUNT_CREATE = 'ACCOUNT CREATE',
    ACCOUNT_UPDATE = 'ACCOUNT UPDATE',
    ACCOUNT_RETRIEVE = 'ACCOUNT RETRIEVE',
    ACCOUNT_GOALS = 'ACCOUNT GOALS',
    ACCOUNT_GOALS_HELPED = 'ACCOUNT GOALS HELPED',
    ACCOUNT_REFUND = 'ACCOUNT REFUND',

    GOAL_COUNT = 'GOAL COUNT',
    GOAL_CREATE = 'GOAL CREATE',
    GOAL_UPDATE = 'GOAL UPDATE',
    GOAL_RETRIEVE = 'GOAL RETRIEVE',
    GOAL_FUND = 'GOAL FUND',
    GOAL_FUNDERS = 'GOAL FUNDERS'
}