export enum ContractActions {
    WALLET_CHECK_CONNECTION = 'WALLET CHECK CONNECTION',
    WALLET_CONNECT = 'WALLET CONNECT',
    ACCOUNT_CREATE = 'ACCOUNT CREATE',
    ACCOUNT_UPDATE = 'ACCOUNT UPDATE',
    ACCOUNT_RETRIEVE = 'ACCOUNT RETRIEVE',
    GOAL_CREATE = 'GOAL CREATE',
    GOAL_UPDATE = 'GOAL UPDATE',
    GOAL_RETRIEVE = 'GOAL RETRIEVE',
    GOAL_FUND = 'GOAL FUND',
}